name: Build and push dockerdl-base image
on:
  schedule:
    # Runs at 00:10 am every Sunday
    - cron: "10 0 * * 0"
  push:
    branches: ["main"]
    paths:
      - "base.Dockerfile"
      - ".github/workflows/docker-publish-base.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "base.Dockerfile"
      - ".github/workflows/docker-publish-base.yml"
  workflow_dispatch:

concurrency:
  group: dockerdl-base-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        CUDA_VER: [12.1.1, 11.7.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            matifali/dockerdl-base
          tags: |
            type=raw,value=${{ matrix.CUDA_VER }}
            type=raw,value=latest,enable=${{ matrix.CUDA_VER == '12.1.1' }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.authors=${{ github.event.repository.owner.login }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: base.Dockerfile
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: CUDA_VER=${{ matrix.CUDA_VER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Readme on dockerhub
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: matifali/dockerdl
          short-description: ${{ github.event.repository.description }}
          readme-filepath: README.md
